[alias]
build-usb-bin = "objcopy --release -- -O binary payload.bin"
build-dtbhax-bin = "objcopy --release --features dtbhax -- -O binary dtbhax.bin"
test-local = "test --target aarch64-apple-darwin"

[build]
target = "ccplex-meow-meow.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
