[alias]
build-payload = "objcopy --profile payload -- -O binary rcmhax-payload.bin"
build-demo-payload = "objcopy --no-default-features --profile payload -- -O binary rcmhax-demo.bin"

[build]
target = "bpmp-katze-none.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
