[alias]
build-payload = "objcopy --profile payload -- -O binary rcmhax-sehax-payload.bin"

[build]
target = "bpmp-katze-none.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
